---
- name: Adding Virtualbox APT repository signature
  apt_key:
    url: "{{ virtualbox_apt_key_link }}"
    state: present

- name: Add support for https
  apt:
    name: apt-transport-https

- name: Adding Virtualbox APT repository
  apt_repository:
    repo: deb {{ virtualbox_apt_repo_link }} {{ ansible_distribution_release }} {{ virtualbox_apt_repo_type }}
    filename: virtualbox
    state: present
    update_cache: yes

- name: install VirtualBox package
  apt:
    name: virtualbox-{{ virtualbox_version }}
    update_cache: yes
