---
- include_tasks: "{{ ansible_os_family }}.yml"

- name: Download Oracle Extension Pack for VirtualBox
  get_url:
    url: "{{ virtualbox_download_site }}/{{ virtualbox_version_full }}/{{ virtualbox_extpack_file }}"
    dest: "/root/{{ virtualbox_extpack_file }}"
    mode: 0644
  when: virtualbox_extpack_install

- name: install Oracle Extension Pack
  shell: VBoxManage extpack install --replace --accept-license={{ virtualbox_extpack_key }} /root/{{ virtualbox_extpack_file }}
  when: virtualbox_extpack_install

- name: Create user for VirtualBox
  user:
    group: "{{ virtualbox_group }}"
    name: "{{ virtualbox_user }}"
    home: "{{ virtualbox_home }}"
  when: virtualbox_create_user

- name: Create VM directory
  file:
    path: "{{ virtualbox_vmdir }}"
    mode: 0775
    owner: "{{ virtualbox_user }}"
    group: "{{ virtualbox_group }}"
  when: virtualbox_create_user

- name: Set VM directory
  become_user: "{{ virtualbox_user }}"
  shell: VBoxManage setproperty machinefolder {{ virtualbox_vmdir }}
  when: virtualbox_create_user