---
- name: Add Virtualbox APT repository signature
  apt_key:
    url: "{{ virtualbox_apt_key_link }}"
  become: yes

- name: Add Virtualbox APT repository
  apt_repository:
    repo: deb [arch=amd64] {{ virtualbox_apt_repo_link }} {{ ansible_distribution_release }} {{ virtualbox_apt_repo_type }}
    update_cache: yes
  become: yes

- name: Install VirtualBox
  apt:
    name: virtualbox-{{ virtualbox_version }}
  become: yes
  register: vb_install

- name: Add user to vbox group
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - vboxusers
    append: yes
  become: yes

- name: Create VM directory
  file:
    path: "{{ virtualbox_vmdir }}"
    state: directory

- name: Set VM directory
  shell: VBoxManage setproperty machinefolder {{ virtualbox_vmdir }}
  become: yes

